chore(import): rename Clubhouse -> Shortcut
linear/linear pull request #175
Opened 2022-01-28 15:08 UTC by jergason

Rename the importer and docs to reflect the new Shortcut name

2022-02-03 18:18 UTC, rlargman requested changes
Thanks for the PR! There are two unrelated files that seem to have gotten caught in this PR: `importIssues.ts` and `TrelloJsonImporter.ts`. Could you remove those two changes? Then it should be good to go.

2022-08-15 14:48 UTC, pacocoursey approved these changes

2022-08-15 14:48 UTC, pacocoursey commented on packages/import/src/importIssues.ts
> -      projectId: (projectId as unknown) as string,
Looks like these are valid prettier changes based on the config. Think we are good to merge @rlargman

2022-08-15 16:06 UTC, rlargman approved these changes

2022-08-15 16:06 UTC, merged