draft: feat(import): add clickup import
linear/linear pull request #220
Opened 2022-10-10 00:14 UTC by de-ar

2023-02-11 00:23 UTC, robcurtis commented
Is this PR getting merged soon? We're interested in moving over from Clickup.

2023-02-11 00:28 UTC, de-ar commented
Earlier I could not test the ClickUp importer. Right now, I'm busy at some other work. So no chance of it being merged anytime soon.

2023-06-15 03:34 UTC, Chew commented
Is there any updates, or do you intend to make some? I'd love to take over otherwise (will credit you as the starting point)

2023-06-15 09:12 UTC, de-ar commented
Hey @Chew!
I do intend to make updates, but my time has become limited. Please do take over and I'm here if you have any questions at all.

2023-06-27 11:02 UTC, akashchouhan16 requested changes

2023-06-27 11:02 UTC, akashchouhan16 commented on package.json
> -  "author": "Linear Orbit, Inc",
The change on this line is not relevant to the PR, could keep it as it was previously.

2023-06-27 11:02 UTC, akashchouhan16 commented on package.json
> -    "build": "run-s generate build:sdk generate:test build:import build:types docs",
Likewise for this line too. Not relevant to the proposed change in this PR.

2023-06-27 11:02 UTC, akashchouhan16 commented on packages/import/package.json
> -  "repository": "https://github.com/linear/linear",
Not a relevant code change

2023-06-27 11:02 UTC, akashchouhan16 commented on packages/import/src/importers/clickupCsv/ClickupCsvImporter.ts
> +  return priorityMap[input] || 0;
Looks good! ⚡

2024-07-03 22:05 UTC, closed without merging